
#TFS to Jira Mapping
mapping:
  UserDefined_1: PROGRAM
  UserDefined_2: PROJECT
  UserDefined_3: FEATURE
  UserStory: STORY
  Task: TASK

#  WARNING
#  Escape Chars \\ needed for JQL
ToSync:
  PROGRAM:
  - Name: Core \\- Commercial Opportunities
    PROJECT:
      - Name: Rebuild Lite Cameras
        FEATURE:
        - Name: OOXML Lite Camera
          STORY: [ 114352, 114991 ]
        - Name: Binary DOC Lite Camera
          STORY: [ 114369 ]
        - Name: Binary PPT Lite Camera
          STORY: [ 113284 ]
        - Name: Binary XLS Lite Camera \\- Bug Fixes
          STORY: [ 114506 ]
        - Name: Spike \\- Release 1.155 Confirm Behavior
          STORY: [ 114688 ]

